version: "3"


services:
  myapp:
    container_name: myapp
#    stdin_open: true
#    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '0.0.0.0:4004:3000'
    command: sh -c "yarn start"
